import { Component, OnInit } from '@angular/core';
import { CarouselConfig } from 'ngx-bootstrap/carousel';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
   providers: [{provide: CarouselConfig, useValue: {interval: 1500, noPause: false}}]
})
export class HomeComponent implements OnInit {
  private contents: Content[]=[
    {"title":"Angular CLI + Bootstrap + D3.js","description":`This app uses
     Bootstrap and Font Awesome with an app generated by Angular CLI. It also 
     uses D3.js v4 to generate dashboard`,"img":"../assets/img/space1.jpg"},
    {"title":"Angular CLI + Bootstrap + D3.js","description":`This app uses
     Bootstrap and Font Awesome with an app generated by Angular CLI. It also
      uses D3.js v4 to generate dashboard`,"img":"../assets/img/space2.jpg"},
    {"title":"Angular CLI + Bootstrap + D3.js","description":`This app uses
     Bootstrap and Font Awesome with an app generated by Angular CLI. It also
      uses D3.js v4 to generate dashboard`,"img":"../assets/img/space3.jpg"}
  ]
  constructor() { }

  ngOnInit() {
  }

}

export interface Content {
  title: string;
  description: string;
  img:string;
}
